version: "3.4"

services:
  php:
    build:
      context: .
      target: frankenphp_dev
    restart: unless-stopped
    depends_on: 
      - database
      - mailer
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: stable
      XDEBUG_MODE: debug
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ^${SERVER_NAME:-example\.com|localhost}|php$$
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./:/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true
    ports:
      - target: 80
        published: 80
        protocol: tcp
        
      - target: 443
        published: 443
        protocol: tcp
        
      - target: 443
        published: 443
        protocol: udp


  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: bbdd
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: user
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  mailer:
    image: rnwood/smtp4dev
    ports: 
      - 3000:80
      - 2525:25

volumes:
  caddy_data:
  caddy_config:
  database_data:
